apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volumeclaim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  claimRef:
          namespace: ukd  
  awsElasticBlockStore:
      volumeID: 
      fsType: ext4
  hostPath:
      path: /opt/eGov/
  resources:
    requests:
      storage: 2Gi