apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: egov
  labels:
    app: phpmyadmin
spec:
  ports:
  - protocol: TCP
    port: 81
    targetPort: 81
  selector:
    app: phpmyadmin
    tier: frontend
  type: LoadBalancer
  