apiVersion: v1
kind: LimitRange
metadata:
  name: wordpress-mysql-memory-limit
  namespace: wordpress-mysql
spec:
  limits:
    - max:
        memory: 8192Mi
      min:
        memory: 2048Mi
      type: Container