apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "ukd-wordpress-volume"
  labels:
    app: wordpress
spec:
  capacity:
    storage: "10Gi" 
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: egov
    name: ukd-wordpress-volume-v1-0
  azureDisk: 
    diskName: wordpress-ukd-volume
    diskURI: /subscriptions/b4e1aa53-c521-44e6-8a4d-5ae107916b5b/resourceGroups/ukd-uat-group/providers/Microsoft.Compute/disks/wordpress-ukd-volume
    kind: Managed
    fsType: ext4  
    readOnly: false

