apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volumeclaim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  claimRef:
        namespace: ukd
  awsElasticBlockStore:
      volumeID: 
      fsType: ext4
  hostPath:
      path: /opt/eGov/  
  resources:
    requests:
      storage: 2Gi
