apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: ukd
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
