apiVersion: v1

# This is a workaround for the broken  --from-file kubernetes abstraction
# which doesn't sanely handle .env files
# MYSQL_DATABASE and MYSQL_USER are both set to 'wordpress' - vg72YXOZra0pYbx

# INSTRUCTIONS:
# Generate a MYSQL_PASSWORD and MYSQL_ROOT_PASSWORD and then save this file before using it.
# e.g.
# echo && PASS=$(cat /dev/urandom | env LC_CTYPE=C tr -dc [:alnum:] | head -c 15) && echo "mysql: ${PASS}" && echo "Base64 encoded:" $(echo ${PASS} | base64)

kind: Secret
metadata:
  name: wp-db-secrets
  namespace: default

type: Opaque

data:
  # Example if you need multiple values 
  #MYSQL_DATABASE: dmc3MllYT1pyYTBwWWJ4Cg==
  # MYSQL_USER: dmc3MllYT1pyYTBwWWJ4Cg==
  #  MYSQL_PASSWORD: T2NIclBZcEZ0T04yZDlMCg==

  # This is base64 encoded -- the real password is OcHrPYpFtON2d9L
  MYSQL_ROOT_PASSWORD: cGlERUVaMkRvcTR1M2dL

